### ISSUE TITLE
how to specify file in outer folder?

### ISSUE THREAD

**Issue by luchianenco** [Farof/heroprotocoljs#1]
how to specify outer folder ?
like that 
node heroprotocol.js replayFile --details /tmp

need possibility to specify an absolute path if possible
thx

**Comment by Farof** [comment]
Right now heroprotocol.js is very basic and provides two modes:
- `--print` prints the requested data to the console (not JSON)
- `--extract` extracts the requested data in the current folder in JSON

If your command is `$ node heroprotocol.js "infernal Shrines (23).StormReplay" --details --extract`, it will create an `Infernal Shrines (23)` directory and output in the `Infernal Shrines (23)/replay.details.json` file. You can't specify an output directory.

You might want to use the `bin/extract.js` tool for that.

```
$ node bin/extract.js "Infernal Shrines (23).StormReplay" /tmp
```

Will extract all the replay data into `/tmp/Infernal Shrines (23)/`.

I plan on adding options to the extraction tool to extract only partial data and not all of it.

Let me know if that does the trick for you!

**Comment by Farof** [comment]
Oh I haven't tested with absolute path though, let me get back to you on that.

**Comment by Farof** [comment]
I can extract to an absolute path on my side, let me know how it goes for you.

**Comment by luchianenco** [comment]
yes it works, but when I run it from PHP script - it doesn't except file path as absolute one...making it relative to script root folder.

P.S. Found in examples how to output...thx for the library =)

**Comment by Farof** [comment]
I'll look into what could be preventing external calls to process the path correctly. Opened #6 for that.

Direct JSON output most probably coming for `heroprotocol.js`
