### ISSUE TITLE
extract.js - add options to only extract certain files

### ISSUE THREAD

**Issue by Farof** [Farof/heroprotocoljs#17]
Right now the extraction tool extract everything. It can take time, especially for the big `replay.game.events` file. Need to add options to only extract certain files, similar to the `heroprotocols.js` ones.

**Comment by jnovack** [comment]
I'll tackle this after #18.  I feel this is valuable for this repo.

**Comment by Farof** [comment]
Done fb8bb189d2d7b83208c6d3c8fd647fc7745b5b3c.
