### ISSUE TITLE
One less abstraction layer...

### ISSUE THREAD

**Issue by jnovack** [Farof/heroprotocoljs#29]
Right now, to use this library one passes in the filename and archive to this library.

Thus the library does two things, extracts AND parses.

I feel additional `.parse()`-only methods should be created in the event the files and header were already extracted from the archive (perhaps a faster, compiled method) via another process.

I propose two convenience methods:
- `parseHeader(buffer)` will parse out and return the header object
- `parseFile(buffer, int version)` will parse a file based on the version supplied.

If there's no objection, I'll start on this.

**Comment by Farof** [comment]
I don't really understand what you mean. Things are already cached as long as you keep references to opened archives so things don't get parsed twice.

Could you provide usescases that you think are problematic with the current API and explain how they are problematic?

**Comment by jnovack** [comment]
The problem is with the extract. The `mpyqjs` library is too slow.

I would like to extract the file with ANOTHER library, but use this library to parse it. My only option to interface with this library currently is sent it a replay, and a variable.

```
const heroprotocol = require('../');
const details = heroprotocol.get(heroprotocol.DETAILS, process.argv[2]);
```

I would LIKE to be able to send it data I've already extracted.

```
const heroprotocol = require('../');
const header = heroprotocol.parseHeader(buffer);
const details = heroprotocol.parseFile(buffer, header.build);
```

Why? Because I can extract files 60% faster using `StormLib` rather than `mpyqs`.  There's little point to rewriting `heroprotocoljs` when it does everything I need, it just does not expose it.

**Extracting 28 replays with `mpyqs`**

```
real 1m43.637s
user 1m35.931s
sys  0m6.731s
```

**Extracting 28 replays with `storm-replay`**

```
real 0m37.774s
user 0m32.481s
sys  0m1.858s
```
