### ISSUE TITLE
_gameLoop in tracker and game events is null

### ISSUE THREAD

**Issue by myrddraall** [Farof/heroprotocoljs#34]
As noted in the reference files the _gameLoop value is always null. this is not the case with the original python lib. Its impossible to track the time events occurred without this

**Comment by Farof** [comment]
Had a look and there is indeed a problem. I didn't know how to port the function and made a guess but it's wrong. Looking at it, thanks.

**Comment by Farof** [comment]
@myrddraall just pushed a correction, thanks for reminding me to do that.

 c91bacc
